### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Pilchie**
* Update TFM to net6.0
* Update all NuGet packages
* Sneak in sorting of Channel names in Index.cshtml

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @wtgodbe @dougbu @BrennanConroy

**Comment by dougbu** [comment]
Suggest cleaning up the warnings before checking this in.
``` text
Warning: /home/runner/work/DependencyFlow/DependencyFlow/Pages/Incoming.cshtml(10,31): warning CS8604: Possible null reference argument for parameter 'source' in 'IOrderedEnumerable<IncomingRepo> Enumerable.OrderBy<IncomingRepo, string>(IEnumerable<IncomingRepo> source, Func<IncomingRepo, string> keySelector)'. [/home/runner/work/DependencyFlow/DependencyFlow/DependencyFlow.csproj]
Warning: /home/runner/work/DependencyFlow/DependencyFlow/Pages/Index.cshtml.cs(41,29): warning CS8604: Possible null reference argument for parameter 'url' in 'RedirectResult PageModel.Redirect(string url)'. [/home/runner/work/DependencyFlow/DependencyFlow/DependencyFlow.csproj]
```

**Comment by Pilchie** [comment]
> Suggest cleaning up the warnings before checking this in.

Fixed in b8704b3

**Review by dougbu — APPROVED** [review]
Very pretty

**Comment by Pilchie** [comment]
This is now successfully deployed after updating azure deploy credentials, and bumping the AppService configuration to .NET 6.

**Comment by BrennanConroy** [comment]
That sort is beautiful 😃

**Comment by dougbu** [comment]
nits:
- The widgets for servicing channels get very confused by incomplete dotnet/runtime releases e.g. <https://dependencyflow.azurewebsites.net/incoming/1296/dotnet/aspnetcore>. The math looks wrong there too.
- For some reason the `Eng` channels only seem to work for dotnet/arcade ☹️

**Comment by Pilchie** [comment]
> * The widgets for servicing channels get very confused by incomplete dotnet/runtime releases e.g. https://dependencyflow.azurewebsites.net/incoming/1296/dotnet/aspnetcore. The math looks wrong there too.

Is that https://github.com/Pilchie/DependencyFlow/issues/4?

> * For some reason the `Eng` channels only seem to work for dotnet/arcade ☹️

Is Arcade the only thing pushed to them?

BTW, PRs welcome ;)

**Comment by dougbu** [comment]
> Is that #4?

Not exactly since those commits aren't "pinned". The symptoms match when looking at a widget. It's just a different root cause for having multiple commits from the upstream repos.

**Comment by dougbu** [comment]
> Is Arcade the only thing pushed to them?

The `*Eng*` channels are weird but Arcade isn't the only repo pushing to them. `darc get-subscriptions --target-repo arcade --channel '.NET Eng - Latest'` shows dotnet/arcade looping back into itself but also dotnet/arcade-validation, dotnet/symreader-converter, and more.

**Pull request merged**
